spring.application.name=CodeGraph

# postgresql
spring.datasource.url=jdbc:postgresql://localhost:5432/CodeGraph_Local
spring.datasource.username=postgres
spring.datasource.password=12345678
spring.datasource.driver-class-name=org.postgresql.Driver

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

logging.level.org.flywaydb=DEBUG
logging.level.org.springframework.boot.autoconfigure.flyway=DEBUG

# MyBatis
mybatis.mapper-locations=classpath:mapper/**/*.xml
mybatis.type-aliases-package=com.CodeGraph.user.model
mybatis.configuration.map-underscore-to-camel-case=true


#email service
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=3000
spring.mail.properties.mail.smtp.writetimeout=5000

#reg, access, refresh  jwt token
koode.jwt.registration-secret=${REGISTRATION_JWT_SECRET}
koode.jwt.registration-expiration-minutes=10

koode.jwt.access-secret=${ACCESS_JWT_SECRET}
koode.jwt.access-expiration-minutes=15

koode.jwt.refresh-secret=${REFRESH_JWT_SECRET}
koode.jwt.refresh-expiration-days=7


# Server
server.port=8081

# Debug
debug=false


spring.autoconfigure.exclude=org.springframework.boot.security.autoconfigure.UserDetailsServiceAutoConfiguration

mybatis.type-handlers-package=com.CodeGraph.common.mybatis